name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install sox

    - name: Generate reference tones
      run: make

    - name: Check existence of generated files
      uses: JJ/files-present-action@releases/v1
      with:
        files: "reference-tones/reference-tones.wav, reference-tones/silence.wav, reference-tones/sine1k.wav, reference-tones/sine10k.wav, reference-tones/sine15k.wav, reference-tones/sine50.wav, reference-tones/sine100.wav"

    - name: List file metadata
      run: |
        ls -lh reference-tones/ | awk '{print $5,$9}'
        file reference-tones/*.wav
