name: Release

on:
  push:
    branches: [ "main" ]

jobs:
  release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3

    - name: Get changed files in the docs folder
      id: makefile-changed
      uses: tj-actions/changed-files@v36
      with:
        files: Makefile

    - name: Prepare release if Makefile changed
      if: steps.makefile-changed.outputs.any_changed == 'true'
      run: |
        sudo apt-get install sox zip
        make release
        ls -lh reference-tones/ | awk '{print $5,$9}'
        file reference-tones/*.wav
        stat reference-tones.zip
    
    - name: Create tag variable
      id: tag
      if: steps.makefile-changed.outputs.any_changed == 'true'
      run: |
        TAG=v$(date +%Y%m%d%H%M)
        echo "$TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT

    - name: Create tag
      if: steps.makefile-changed.outputs.any_changed == 'true'
      uses: rickstaa/action-create-tag@v1
      with:
        tag: ${{ steps.tag.outputs.tag }}

    - name: Release
      if: steps.makefile-changed.outputs.any_changed == 'true'
      uses: softprops/action-gh-release@v1
      with:
        body_path: ReleaseNotes.template.md
        files: reference-tones.zip
        fail_on_unmatched_files: true
        tag_name: ${{ steps.tag.outputs.tag }}
        name: Reference Tones ${{ steps.tag.outputs.tag }}
